# Generated by Django 4.2.29 on 2026-04-07 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_index', models.IntegerField(help_text='显卡编号1-8', unique=True)),
                ('name', models.CharField(help_text='显卡名称', max_length=20)),
                ('status', models.CharField(choices=[('idle', '空闲'), ('occupied', '占用中'), ('maintenance', '维护中')], default='idle', max_length=20)),
                ('description', models.TextField(blank=True, help_text='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '显卡',
                'verbose_name_plural': '显卡',
                'db_table': 'gpus',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True, verbose_name='备注/拒绝理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.gpu', verbose_name='显卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '预约申请',
                'verbose_name_plural': '预约申请',
                'db_table': 'reservations',
                'indexes': [models.Index(fields=['gpu', 'start_time', 'end_time'], name='reservation_gpu_id_1f199f_idx'), models.Index(fields=['user', 'status'], name='reservation_user_id_d4fda7_idx'), models.Index(fields=['status', 'start_time'], name='reservation_status_50e83a_idx')],
            },
        ),
    ]
