# Generated by Django 4.2.29 on 2026-04-07 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SudoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sudo_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': 'Sudo权限申请',
                'verbose_name_plural': 'Sudo权限申请',
                'db_table': 'sudo_requests',
                'indexes': [models.Index(fields=['user', 'status'], name='sudo_reques_user_id_8106f4_idx'), models.Index(fields=['status', 'valid_until'], name='sudo_reques_status_183418_idx')],
            },
        ),
    ]
